@tiatania.API_HostAddress = http://localhost:5246

GET {{tiatania.API_HostAddress}}/API/Weatherforecasts/
Accept: application/json

###

GET {{tiatania.API_HostAddress}}/API/Menus/
Accept: application/json

###
